<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RivetRoot)/platform/dotnet/Rivet.Runtime/Rivet.Runtime.csproj" />
    <Compile Include="../../../dotnet/GeneratedBackend.cs" Link="GeneratedBackend.cs" />
  </ItemGroup>
</Project>
