// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "taskly";
inline constexpr char kVersion[] = "1.4.1";
inline constexpr std::int64_t kBuild = 1;
inline constexpr char kIdentifier[] = "app.taskly.Taskly";
inline constexpr char kReleaseChannel[] = "stable";

struct QuickAddParse {
  std::string text;
  std::optional<std::string> due_date;
  std::optional<std::string> due_time;
};

struct Settings {
  std::string language;
  std::string theme;
  std::string close_to_tray;
  std::int64_t last_selected_list_id;
  std::string database_path;
};

struct SmartCounts {
  std::int64_t today;
  std::int64_t planned;
  std::int64_t all;
  std::int64_t completed;
};

struct TodoList {
  std::int64_t id;
  std::string name;
  std::optional<std::string> icon;
  std::optional<std::int64_t> color;
  std::int64_t pending_count;
};

struct Task {
  std::int64_t id;
  std::int64_t list_id;
  std::optional<std::string> list_name;
  std::string text;
  bool completed;
  std::optional<std::string> due_date;
  std::optional<std::string> due_time;
  std::optional<std::string> notes;
  std::string created_at;
};

struct Snapshot {
  SmartCounts counts;
  std::vector<TodoList> lists;
  std::vector<Task> tasks;
};

struct UpdateCheck {
  std::string status;
  std::optional<std::string> error;
  std::string current_version;
  std::optional<std::string> available_version;
  std::optional<std::int64_t> build;
  std::optional<std::string> published_at;
  std::optional<std::string> installer;
  std::optional<std::int64_t> size_bytes;
};

struct UpdateState {
  std::string phase;
  std::int64_t percent;
  std::optional<std::string> message;
  std::optional<std::string> downloaded_path;
  std::optional<std::string> available_version;
};

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode__Optional_Int64_(std::optional<std::int64_t> const& v) { return v ? encode_Int64(*v) : rivet::Value{}; }
inline rivet::Value encode__Optional_String_(std::optional<std::string> const& v) { return v ? encode_String(*v) : rivet::Value{}; }
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_Task(Task const& v) { rivet::Value::List r; r.reserve(9); r.push_back(encode_Int64(v.id)); r.push_back(encode_Int64(v.list_id)); r.push_back(encode__Optional_String_(v.list_name)); r.push_back(encode_String(v.text)); r.push_back(encode_Bool(v.completed)); r.push_back(encode__Optional_String_(v.due_date)); r.push_back(encode__Optional_String_(v.due_time)); r.push_back(encode__Optional_String_(v.notes)); r.push_back(encode_String(v.created_at)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_UpdateCheck(UpdateCheck const& v) { rivet::Value::List r; r.reserve(8); r.push_back(encode_String(v.status)); r.push_back(encode__Optional_String_(v.error)); r.push_back(encode_String(v.current_version)); r.push_back(encode__Optional_String_(v.available_version)); r.push_back(encode__Optional_Int64_(v.build)); r.push_back(encode__Optional_String_(v.published_at)); r.push_back(encode__Optional_String_(v.installer)); r.push_back(encode__Optional_Int64_(v.size_bytes)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Void() { return rivet::Value{}; }
inline rivet::Value encode_TodoList(TodoList const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_Int64(v.id)); r.push_back(encode_String(v.name)); r.push_back(encode__Optional_String_(v.icon)); r.push_back(encode__Optional_Int64_(v.color)); r.push_back(encode_Int64(v.pending_count)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Settings(Settings const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_String(v.language)); r.push_back(encode_String(v.theme)); r.push_back(encode_String(v.close_to_tray)); r.push_back(encode_Int64(v.last_selected_list_id)); r.push_back(encode_String(v.database_path)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_SmartCounts(SmartCounts const& v) { rivet::Value::List r; r.reserve(4); r.push_back(encode_Int64(v.today)); r.push_back(encode_Int64(v.planned)); r.push_back(encode_Int64(v.all)); r.push_back(encode_Int64(v.completed)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_TodoList_(std::vector<TodoList> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_TodoList(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_Task_(std::vector<Task> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_Task(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Snapshot(Snapshot const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_SmartCounts(v.counts)); r.push_back(encode__List_TodoList_(v.lists)); r.push_back(encode__List_Task_(v.tasks)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_QuickAddParse(QuickAddParse const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_String(v.text)); r.push_back(encode__Optional_String_(v.due_date)); r.push_back(encode__Optional_String_(v.due_time)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_UpdateState(UpdateState const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_String(v.phase)); r.push_back(encode_Int64(v.percent)); r.push_back(encode__Optional_String_(v.message)); r.push_back(encode__Optional_String_(v.downloaded_path)); r.push_back(encode__Optional_String_(v.available_version)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Any(rivet::Value v) { return v; }

inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline std::optional<std::int64_t> decode__Optional_Int64_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_Int64(v); }
inline std::optional<std::string> decode__Optional_String_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_String(v); }
inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline Task decode_Task(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 9) throw std::runtime_error("Rivet result type mismatch: Task"); return Task{decode_Int64((*p)[0]), decode_Int64((*p)[1]), decode__Optional_String_((*p)[2]), decode_String((*p)[3]), decode_Bool((*p)[4]), decode__Optional_String_((*p)[5]), decode__Optional_String_((*p)[6]), decode__Optional_String_((*p)[7]), decode_String((*p)[8])}; }
inline UpdateCheck decode_UpdateCheck(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 8) throw std::runtime_error("Rivet result type mismatch: UpdateCheck"); return UpdateCheck{decode_String((*p)[0]), decode__Optional_String_((*p)[1]), decode_String((*p)[2]), decode__Optional_String_((*p)[3]), decode__Optional_Int64_((*p)[4]), decode__Optional_String_((*p)[5]), decode__Optional_String_((*p)[6]), decode__Optional_Int64_((*p)[7])}; }
inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
inline TodoList decode_TodoList(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: TodoList"); return TodoList{decode_Int64((*p)[0]), decode_String((*p)[1]), decode__Optional_String_((*p)[2]), decode__Optional_Int64_((*p)[3]), decode_Int64((*p)[4])}; }
inline Settings decode_Settings(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: Settings"); return Settings{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_Int64((*p)[3]), decode_String((*p)[4])}; }
inline SmartCounts decode_SmartCounts(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 4) throw std::runtime_error("Rivet result type mismatch: SmartCounts"); return SmartCounts{decode_Int64((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2]), decode_Int64((*p)[3])}; }
inline std::vector<TodoList> decode__List_TodoList_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List TodoList)"); std::vector<TodoList> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_TodoList(x)); return r; }
inline std::vector<Task> decode__List_Task_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List Task)"); std::vector<Task> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_Task(x)); return r; }
inline Snapshot decode_Snapshot(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: Snapshot"); return Snapshot{decode_SmartCounts((*p)[0]), decode__List_TodoList_((*p)[1]), decode__List_Task_((*p)[2])}; }
inline QuickAddParse decode_QuickAddParse(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: QuickAddParse"); return QuickAddParse{decode_String((*p)[0]), decode__Optional_String_((*p)[1]), decode__Optional_String_((*p)[2])}; }
inline UpdateState decode_UpdateState(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: UpdateState"); return UpdateState{decode_String((*p)[0]), decode_Int64((*p)[1]), decode__Optional_String_((*p)[2]), decode__Optional_String_((*p)[3]), decode__Optional_String_((*p)[4])}; }
inline rivet::Value decode_Any(rivet::Value const& v) { return v; }
}  // namespace detail

struct ChangedEvent { rivet::Value value; };
using Event = std::variant<ChangedEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "changed") return Event{ChangedEvent{detail::decode_Any(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::windows::Backend& backend) : backend_(backend) {}

  std::future<Task> add_task(std::string text, std::optional<std::int64_t> list_id, std::optional<std::string> due_date, std::optional<std::string> due_time, std::optional<std::string> notes) { auto raw = backend_.call("add_task", rivet::Value::List{detail::encode_String(text), detail::encode__Optional_Int64_(list_id), detail::encode__Optional_String_(due_date), detail::encode__Optional_String_(due_time), detail::encode__Optional_String_(notes)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Task { return detail::decode_Task(raw.get()); }); }
  [[nodiscard]] std::uint64_t add_task_async(std::string text, std::optional<std::int64_t> list_id, std::optional<std::string> due_date, std::optional<std::string> due_time, std::optional<std::string> notes, std::function<void(Result<Task>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("add_task", rivet::Value::List{detail::encode_String(text), detail::encode__Optional_Int64_(list_id), detail::encode__Optional_String_(due_date), detail::encode__Optional_String_(due_time), detail::encode__Optional_String_(notes)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<Task> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Task(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<UpdateCheck> check_updates() { auto raw = backend_.call("check_updates", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> UpdateCheck { return detail::decode_UpdateCheck(raw.get()); }); }
  [[nodiscard]] std::uint64_t check_updates_async(std::function<void(Result<UpdateCheck>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("check_updates", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<UpdateCheck> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_UpdateCheck(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> close_database() { auto raw = backend_.call("close_database", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t close_database_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("close_database", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<TodoList> create_list(std::string name, std::optional<std::string> icon, std::optional<std::int64_t> color) { auto raw = backend_.call("create_list", rivet::Value::List{detail::encode_String(name), detail::encode__Optional_String_(icon), detail::encode__Optional_Int64_(color)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> TodoList { return detail::decode_TodoList(raw.get()); }); }
  [[nodiscard]] std::uint64_t create_list_async(std::string name, std::optional<std::string> icon, std::optional<std::int64_t> color, std::function<void(Result<TodoList>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("create_list", rivet::Value::List{detail::encode_String(name), detail::encode__Optional_String_(icon), detail::encode__Optional_Int64_(color)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<TodoList> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_TodoList(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> default_database() { auto raw = backend_.call("default_database", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t default_database_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("default_database", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<bool> delete_list(std::int64_t id) { auto raw = backend_.call("delete_list", rivet::Value::List{detail::encode_Int64(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> bool { return detail::decode_Bool(raw.get()); }); }
  [[nodiscard]] std::uint64_t delete_list_async(std::int64_t id, std::function<void(Result<bool>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("delete_list", rivet::Value::List{detail::encode_Int64(id)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<bool> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bool(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<bool> delete_task(std::int64_t id) { auto raw = backend_.call("delete_task", rivet::Value::List{detail::encode_Int64(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> bool { return detail::decode_Bool(raw.get()); }); }
  [[nodiscard]] std::uint64_t delete_task_async(std::int64_t id, std::function<void(Result<bool>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("delete_task", rivet::Value::List{detail::encode_Int64(id)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<bool> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bool(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> get_setting(std::string key) { auto raw = backend_.call("get_setting", rivet::Value::List{detail::encode_String(key)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_setting_async(std::string key, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get_setting", rivet::Value::List{detail::encode_String(key)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Settings> get_settings() { auto raw = backend_.call("get_settings", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Settings { return detail::decode_Settings(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_settings_async(std::function<void(Result<Settings>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get_settings", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<Settings> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Settings(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Snapshot> load_snapshot(std::string view, std::optional<std::int64_t> list_id, bool show_completed) { auto raw = backend_.call("load_snapshot", rivet::Value::List{detail::encode_String(view), detail::encode__Optional_Int64_(list_id), detail::encode_Bool(show_completed)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Snapshot { return detail::decode_Snapshot(raw.get()); }); }
  [[nodiscard]] std::uint64_t load_snapshot_async(std::string view, std::optional<std::int64_t> list_id, bool show_completed, std::function<void(Result<Snapshot>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("load_snapshot", rivet::Value::List{detail::encode_String(view), detail::encode__Optional_Int64_(list_id), detail::encode_Bool(show_completed)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<Snapshot> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Snapshot(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Snapshot> open_database(std::string path) { auto raw = backend_.call("open_database", rivet::Value::List{detail::encode_String(path)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Snapshot { return detail::decode_Snapshot(raw.get()); }); }
  [[nodiscard]] std::uint64_t open_database_async(std::string path, std::function<void(Result<Snapshot>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("open_database", rivet::Value::List{detail::encode_String(path)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<Snapshot> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Snapshot(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> parse_due(std::string expression) { auto raw = backend_.call("parse_due", rivet::Value::List{detail::encode_String(expression)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t parse_due_async(std::string expression, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("parse_due", rivet::Value::List{detail::encode_String(expression)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<QuickAddParse> parse_quick_add(std::string text) { auto raw = backend_.call("parse_quick_add", rivet::Value::List{detail::encode_String(text)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> QuickAddParse { return detail::decode_QuickAddParse(raw.get()); }); }
  [[nodiscard]] std::uint64_t parse_quick_add_async(std::string text, std::function<void(Result<QuickAddParse>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("parse_quick_add", rivet::Value::List{detail::encode_String(text)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<QuickAddParse> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_QuickAddParse(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<Task>> search_tasks(std::string keyword) { auto raw = backend_.call("search_tasks", rivet::Value::List{detail::encode_String(keyword)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<Task> { return detail::decode__List_Task_(raw.get()); }); }
  [[nodiscard]] std::uint64_t search_tasks_async(std::string keyword, std::function<void(Result<std::vector<Task>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("search_tasks", rivet::Value::List{detail::encode_String(keyword)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<Task>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_Task_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Task> set_completed(std::int64_t id, bool completed) { auto raw = backend_.call("set_completed", rivet::Value::List{detail::encode_Int64(id), detail::encode_Bool(completed)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Task { return detail::decode_Task(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_completed_async(std::int64_t id, bool completed, std::function<void(Result<Task>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("set_completed", rivet::Value::List{detail::encode_Int64(id), detail::encode_Bool(completed)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<Task> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Task(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Settings> set_setting(std::string key, std::string value) { auto raw = backend_.call("set_setting", rivet::Value::List{detail::encode_String(key), detail::encode_String(value)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Settings { return detail::decode_Settings(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_setting_async(std::string key, std::string value, std::function<void(Result<Settings>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("set_setting", rivet::Value::List{detail::encode_String(key), detail::encode_String(value)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<Settings> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Settings(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> start_download() { auto raw = backend_.call("start_download", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t start_download_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("start_download", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<TodoList> update_list(TodoList item) { auto raw = backend_.call("update_list", rivet::Value::List{detail::encode_TodoList(item)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> TodoList { return detail::decode_TodoList(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_list_async(TodoList item, std::function<void(Result<TodoList>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update_list", rivet::Value::List{detail::encode_TodoList(item)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<TodoList> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_TodoList(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<UpdateState> update_state() { auto raw = backend_.call("update_state", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> UpdateState { return detail::decode_UpdateState(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_state_async(std::function<void(Result<UpdateState>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update_state", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<UpdateState> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_UpdateState(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Task> update_task(Task task) { auto raw = backend_.call("update_task", rivet::Value::List{detail::encode_Task(task)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Task { return detail::decode_Task(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_task_async(Task task, std::function<void(Result<Task>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update_task", rivet::Value::List{detail::encode_Task(task)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<Task> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Task(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<Task> update_task_text(std::int64_t id, std::string text) { auto raw = backend_.call("update_task_text", rivet::Value::List{detail::encode_Int64(id), detail::encode_String(text)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Task { return detail::decode_Task(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_task_text_async(std::int64_t id, std::string text, std::function<void(Result<Task>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update_task_text", rivet::Value::List{detail::encode_Int64(id), detail::encode_String(text)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<Task> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Task(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::windows::Backend& backend_;
};

}  // namespace rivet_app
