// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";

struct SmartCounts {
  std::int64_t today;
  std::int64_t planned;
  std::int64_t all;
  std::int64_t completed;
};

struct TodoList {
  std::int64_t id;
  std::string name;
  std::optional<std::string> icon;
  std::optional<std::int64_t> color;
  std::int64_t pending_count;
};

struct Task {
  std::int64_t id;
  std::int64_t list_id;
  std::optional<std::string> list_name;
  std::string text;
  bool completed;
  std::optional<std::string> due_date;
  std::optional<std::string> due_time;
  std::optional<std::string> notes;
  std::string created_at;
};

struct Snapshot {
  SmartCounts counts;
  std::vector<TodoList> lists;
  std::vector<Task> tasks;
};

namespace detail {
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode__Optional_Int64_(std::optional<std::int64_t> const& v) { return v ? encode_Int64(*v) : rivet::Value{}; }
inline rivet::Value encode__Optional_String_(std::optional<std::string> const& v) { return v ? encode_String(*v) : rivet::Value{}; }
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_Task(Task const& v) { rivet::Value::List r; r.reserve(9); r.push_back(encode_Int64(v.id)); r.push_back(encode_Int64(v.list_id)); r.push_back(encode__Optional_String_(v.list_name)); r.push_back(encode_String(v.text)); r.push_back(encode_Bool(v.completed)); r.push_back(encode__Optional_String_(v.due_date)); r.push_back(encode__Optional_String_(v.due_time)); r.push_back(encode__Optional_String_(v.notes)); r.push_back(encode_String(v.created_at)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Void() { return rivet::Value{}; }
inline rivet::Value encode_TodoList(TodoList const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_Int64(v.id)); r.push_back(encode_String(v.name)); r.push_back(encode__Optional_String_(v.icon)); r.push_back(encode__Optional_Int64_(v.color)); r.push_back(encode_Int64(v.pending_count)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_SmartCounts(SmartCounts const& v) { rivet::Value::List r; r.reserve(4); r.push_back(encode_Int64(v.today)); r.push_back(encode_Int64(v.planned)); r.push_back(encode_Int64(v.all)); r.push_back(encode_Int64(v.completed)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_TodoList_(std::vector<TodoList> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_TodoList(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_Task_(std::vector<Task> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_Task(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Snapshot(Snapshot const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_SmartCounts(v.counts)); r.push_back(encode__List_TodoList_(v.lists)); r.push_back(encode__List_Task_(v.tasks)); return rivet::Value(std::move(r)); }

inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline std::optional<std::int64_t> decode__Optional_Int64_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_Int64(v); }
inline std::optional<std::string> decode__Optional_String_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_String(v); }
inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline Task decode_Task(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 9) throw std::runtime_error("Rivet result type mismatch: Task"); return Task{decode_Int64((*p)[0]), decode_Int64((*p)[1]), decode__Optional_String_((*p)[2]), decode_String((*p)[3]), decode_Bool((*p)[4]), decode__Optional_String_((*p)[5]), decode__Optional_String_((*p)[6]), decode__Optional_String_((*p)[7]), decode_String((*p)[8])}; }
inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
inline TodoList decode_TodoList(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: TodoList"); return TodoList{decode_Int64((*p)[0]), decode_String((*p)[1]), decode__Optional_String_((*p)[2]), decode__Optional_Int64_((*p)[3]), decode_Int64((*p)[4])}; }
inline SmartCounts decode_SmartCounts(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 4) throw std::runtime_error("Rivet result type mismatch: SmartCounts"); return SmartCounts{decode_Int64((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2]), decode_Int64((*p)[3])}; }
inline std::vector<TodoList> decode__List_TodoList_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List TodoList)"); std::vector<TodoList> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_TodoList(x)); return r; }
inline std::vector<Task> decode__List_Task_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List Task)"); std::vector<Task> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_Task(x)); return r; }
inline Snapshot decode_Snapshot(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: Snapshot"); return Snapshot{decode_SmartCounts((*p)[0]), decode__List_TodoList_((*p)[1]), decode__List_Task_((*p)[2])}; }
}  // namespace detail

class API {
 public:
  explicit API(rivet::windows::Backend& backend) : backend_(backend) {}

  std::future<Task> add_task(std::string text, std::optional<std::int64_t> list_id, std::optional<std::string> due_date, std::optional<std::string> due_time, std::optional<std::string> notes) { auto raw = backend_.call("add_task", rivet::Value::List{detail::encode_String(text), detail::encode__Optional_Int64_(list_id), detail::encode__Optional_String_(due_date), detail::encode__Optional_String_(due_time), detail::encode__Optional_String_(notes)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Task { return detail::decode_Task(raw.get()); }); }
  std::future<void> close_database() { auto raw = backend_.call("close_database", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  std::future<TodoList> create_list(std::string name, std::optional<std::string> icon, std::optional<std::int64_t> color) { auto raw = backend_.call("create_list", rivet::Value::List{detail::encode_String(name), detail::encode__Optional_String_(icon), detail::encode__Optional_Int64_(color)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> TodoList { return detail::decode_TodoList(raw.get()); }); }
  std::future<bool> delete_list(std::int64_t id) { auto raw = backend_.call("delete_list", rivet::Value::List{detail::encode_Int64(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> bool { return detail::decode_Bool(raw.get()); }); }
  std::future<bool> delete_task(std::int64_t id) { auto raw = backend_.call("delete_task", rivet::Value::List{detail::encode_Int64(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> bool { return detail::decode_Bool(raw.get()); }); }
  std::future<Snapshot> load_snapshot(std::string view, std::optional<std::int64_t> list_id, bool show_completed) { auto raw = backend_.call("load_snapshot", rivet::Value::List{detail::encode_String(view), detail::encode__Optional_Int64_(list_id), detail::encode_Bool(show_completed)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Snapshot { return detail::decode_Snapshot(raw.get()); }); }
  std::future<Snapshot> open_database(std::string path) { auto raw = backend_.call("open_database", rivet::Value::List{detail::encode_String(path)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Snapshot { return detail::decode_Snapshot(raw.get()); }); }
  std::future<std::vector<Task>> search_tasks(std::string keyword) { auto raw = backend_.call("search_tasks", rivet::Value::List{detail::encode_String(keyword)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<Task> { return detail::decode__List_Task_(raw.get()); }); }
  std::future<Task> set_completed(std::int64_t id, bool completed) { auto raw = backend_.call("set_completed", rivet::Value::List{detail::encode_Int64(id), detail::encode_Bool(completed)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Task { return detail::decode_Task(raw.get()); }); }
  std::future<TodoList> update_list(TodoList item) { auto raw = backend_.call("update_list", rivet::Value::List{detail::encode_TodoList(item)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> TodoList { return detail::decode_TodoList(raw.get()); }); }
  std::future<Task> update_task(Task task) { auto raw = backend_.call("update_task", rivet::Value::List{detail::encode_Task(task)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Task { return detail::decode_Task(raw.get()); }); }
  std::future<Task> update_task_text(std::int64_t id, std::string text) { auto raw = backend_.call("update_task_text", rivet::Value::List{detail::encode_Int64(id), detail::encode_String(text)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Task { return detail::decode_Task(raw.get()); }); }

 private:
  rivet::windows::Backend& backend_;
};

}  // namespace rivet_app
