import Foundation

/// App directory layout (shared contract with the other platforms):
/// app dir ~/.taskly/, default DB ~/.taskly/tasks.db, config ~/.taskly/config.ini.
public enum PathUtils {
    public static let appDirName = ".taskly"
    public static let defaultDatabaseFileName = "tasks.db"
    public static let configFileName = "config.ini"

    /// ~/.taskly, created on demand.
    public static var appDirectory: String {
        let dir = homeDirectory + "/" + appDirName
        if !FileManager.default.fileExists(atPath: dir) {
            try? FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
        }
        return dir
    }

    public static var defaultDatabasePath: String { appDirectory + "/" + defaultDatabaseFileName }
    public static var configPath: String { appDirectory + "/" + configFileName }

    public static var homeDirectory: String {
        if let home = ProcessInfo.processInfo.environment["HOME"], !home.isEmpty {
            return home
        }
        return NSHomeDirectory()
    }
}

/// INI-style config at ~/.taskly/config.ini (key=value, ';'/'#' comments).
/// Keys are a cross-platform contract: last-db-path (legacy last_db_path),
/// language (zh/en, default zh), last-selected-list-id.
public final class ConfigService: @unchecked Sendable {
    private let configPath: String
    private var values: [String: String] = [:]
    private let lock = NSLock()

    public init(configPath: String = PathUtils.configPath) {
        self.configPath = configPath
    }

    public func load() {
        lock.lock(); defer { lock.unlock() }
        values = [:]
        guard FileManager.default.fileExists(atPath: configPath),
              let raw = FileManager.default.contents(atPath: configPath),
              let content = String(data: raw, encoding: .utf8) else { return }

        for rawLine in content.components(separatedBy: .newlines) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            if line.isEmpty || line.hasPrefix(";") || line.hasPrefix("#") { continue }
            guard let eq = line.firstIndex(of: "="), eq != line.startIndex else { continue }
            let key = String(line[..<eq]).trimmingCharacters(in: .whitespaces)
            let value = String(line[line.index(after: eq)...]).trimmingCharacters(in: .whitespaces)
            values[key] = value
        }
    }

    public func save() {
        lock.lock(); defer { lock.unlock() }
        var lines = [
            "# Taskly configuration",
            "# This file is automatically generated and managed by Taskly.",
        ]
        for (key, value) in values.sorted(by: { $0.key < $1.key }) {
            lines.append("\(key)=\(value)")
        }
        let content = lines.joined(separator: "\n") + "\n"
        let dir = (configPath as NSString).deletingLastPathComponent
        if !dir.isEmpty && !FileManager.default.fileExists(atPath: dir) {
            try? FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
        }
        try? content.write(toFile: configPath, atomically: true, encoding: .utf8)
    }

    public func get(_ key: String, _ defaultValue: String = "") -> String {
        lock.lock(); defer { lock.unlock() }
        if let v = values[key] { return v }
        // Legacy key name compatibility.
        if key == "last-db-path", let legacy = values["last_db_path"] { return legacy }
        return defaultValue
    }

    public func set(_ key: String, _ value: String) {
        lock.lock(); defer { lock.unlock() }
        values[key] = value
    }

    public var lastDbPath: String {
        get { get("last-db-path", "") }
        set { set("last-db-path", newValue) }
    }

    /// zh / en, default zh.
    public var language: String {
        get { get("language", "zh") }
        set { set("language", newValue) }
    }

    public var lastSelectedListId: Int {
        get { Int(get("last-selected-list-id", "0")) ?? 0 }
        set { set("last-selected-list-id", String(newValue)) }
    }
}

/// Input validation limits (cross-platform contract).
public enum ValidationHelper {
    public static let maxTaskTextLength = 1000
    public static let maxListNameLength = 100
    public static let maxSearchKeywordLength = 200
    public static let minYear = 1900
    public static let maxYear = 2100

    public static func validateTaskText(_ text: String, _ i18n: I18nService) -> AppError? {
        if text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return AppError(i18n.t("errorEnterTaskDesc"), .validation)
        }
        if text.count > maxTaskTextLength {
            return AppError(i18n.format("errorTaskDescTooLong", maxTaskTextLength), .validation)
        }
        return nil
    }

    public static func validateListName(_ name: String, _ i18n: I18nService) -> AppError? {
        if name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return AppError(i18n.t("errorEnterListName"), .validation)
        }
        if name.count > maxListNameLength {
            return AppError(i18n.format("errorListNameTooLong", maxListNameLength), .validation)
        }
        return nil
    }

    public static func validateSearchKeyword(_ keyword: String, _ i18n: I18nService) -> AppError? {
        if keyword.count > maxSearchKeywordLength {
            return AppError(
                i18n.format("errorSearchKeywordTooLong", maxSearchKeywordLength), .validation)
        }
        return nil
    }
}
