using System.Globalization;

namespace Taskly.Data;

/// <summary>
/// INI config at ~/.taskly/config.ini (key=value, ';'/'#' comments).
/// Keys: last-db-path (legacy last_db_path), language, last-selected-list-id.
/// </summary>
public sealed class ConfigService
{
    private readonly string _configPath;
    private Dictionary<string, string> _values = new(StringComparer.OrdinalIgnoreCase);

    public ConfigService()
    {
        _configPath = PathUtils.GetConfigPath();
    }

    public void Load()
    {
        _values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (!File.Exists(_configPath))
        {
            return;
        }

        try
        {
            foreach (var raw in File.ReadAllLines(_configPath))
            {
                var line = raw.Trim();
                if (line.Length == 0 || line.StartsWith(';') || line.StartsWith('#'))
                {
                    continue;
                }

                var eq = line.IndexOf('=');
                if (eq <= 0)
                {
                    continue;
                }

                var key = line[..eq].Trim();
                var value = line[(eq + 1)..].Trim();
                _values[key] = value;
            }
        }
        catch
        {
            // Unreadable config → empty defaults.
        }
    }

    public void Save()
    {
        try
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("# Taskly configuration");
            sb.AppendLine("# This file is automatically generated and managed by Taskly.");
            foreach (var kv in _values)
            {
                sb.Append(kv.Key).Append('=').AppendLine(kv.Value);
            }

            File.WriteAllText(_configPath, sb.ToString());
        }
        catch
        {
            // Config write failure is non-fatal.
        }
    }

    public string Get(string key, string defaultValue = "")
    {
        if (_values.TryGetValue(key, out var v))
        {
            return v;
        }

        if (key == "last-db-path" && _values.TryGetValue("last_db_path", out var legacy))
        {
            return legacy;
        }

        return defaultValue;
    }

    public void Set(string key, string value) => _values[key] = value;

    public string LastDbPath
    {
        get => Get("last-db-path", string.Empty);
        set => Set("last-db-path", value);
    }

    public string Language
    {
        get => Get("language", "zh");
        set => Set("language", value);
    }

    public int LastSelectedListId
    {
        get => int.TryParse(Get("last-selected-list-id", "0"), CultureInfo.InvariantCulture, out var id) ? id : 0;
        set => Set("last-selected-list-id", value.ToString(CultureInfo.InvariantCulture));
    }
}
