// Taskly — app directory layout + config.ini (contract: DATA-FORMAT.md §1/§7).

namespace Taskly {

public class Config : Object {
    public const string APP_DIR_NAME = ".taskly";
    public const string DEFAULT_DB_FILE = "tasks.db";
    public const string CONFIG_FILE = "config.ini";

    private GLib.HashTable<string, string> values;
    public string config_path { get; private set; }

    public Config() {
        values = new GLib.HashTable<string, string>(str_hash, str_equal);
        config_path = Path.build_filename(home_directory(), APP_DIR_NAME, CONFIG_FILE);
        load();
    }

    public static string home_directory() {
        var home = Environment.get_variable("HOME");
        return (home != null && home.length > 0) ? home : Environment.get_home_dir();
    }

    public static string app_directory() {
        var dir = Path.build_filename(home_directory(), APP_DIR_NAME);
        DirUtils.create_with_parents(dir, 0755);
        return dir;
    }

    public static string default_database_path() {
        return Path.build_filename(app_directory(), DEFAULT_DB_FILE);
    }

    // INI: key=value lines, ';'/'#' comments; keys case-insensitive.
    public void load() {
        values.remove_all();
        string content;
        try {
            FileUtils.get_contents(config_path, out content);
        } catch (Error e) {
            return; // missing/unreadable config → empty defaults
        }

        foreach (var raw in content.split("\n")) {
            var line = raw.strip();
            if (line.length == 0 || line.has_prefix(";") || line.has_prefix("#")) {
                continue;
            }
            var eq = line.index_of("=");
            if (eq <= 0) {
                continue;
            }
            var key = line.substring(0, eq).strip().down();
            var value = line.substring(eq + 1).strip();
            values[key] = value;
        }
    }

    public void save() {
        var sb = new StringBuilder();
        sb.append("# Taskly configuration\n");
        sb.append("# This file is automatically generated and managed by Taskly.\n");
        var keys = new GLib.List<string>();
        foreach (var key in values.get_keys()) {
            keys.append(key);
        }
        keys.sort((a, b) => strcmp(a, b));
        foreach (var key in keys) {
            sb.append_printf("%s=%s\n", key, values[key]);
        }
        var dir = Path.get_dirname(config_path);
        DirUtils.create_with_parents(dir, 0755);
        try {
            FileUtils.set_contents(config_path, sb.str);
        } catch (Error e) {
            // Config write failure is non-fatal.
        }
    }

    public string? get_value(string key) {
        return values.lookup(key.down());
    }

    public void set_value(string key, string value) {
        values[key.down()] = value;
    }

    public string? last_db_path() {
        var v = get_value("last-db-path");
        if (v == null) {
            v = get_value("last_db_path"); // legacy key name
        }
        return (v != null && v.length > 0) ? v : null;
    }

    public string language() {
        var v = get_value("language");
        return (v != null && v.length > 0) ? v : "zh";
    }

    public int64 last_selected_list_id() {
        var v = get_value("last-selected-list-id");
        if (v == null) {
            return 0;
        }
        return int64.parse(v);
    }

    public void set_last_selected_list_id(int64 id) {
        set_value("last-selected-list-id", id.to_string());
        save();
    }
}

}
