//! Paths + config.ini (contract: DATA-FORMAT.md §1/§7).

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

pub const APP_DIR_NAME: &str = ".taskly";
pub const DEFAULT_DB_FILE: &str = "tasks.db";
pub const CONFIG_FILE: &str = "config.ini";

pub fn home_directory() -> PathBuf {
    std::env::var("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/"))
}

pub fn app_directory() -> PathBuf {
    let dir = home_directory().join(APP_DIR_NAME);
    let _ = fs::create_dir_all(&dir);
    dir
}

pub fn default_database_path() -> PathBuf {
    app_directory().join(DEFAULT_DB_FILE)
}

pub fn config_path() -> PathBuf {
    app_directory().join(CONFIG_FILE)
}

/// INI config: key=value lines, ';'/'#' comments, case-insensitive keys.
pub struct Config {
    values: HashMap<String, String>,
    path: PathBuf,
}

impl Config {
    pub fn load() -> Self {
        let path = config_path();
        let mut config = Self { values: HashMap::new(), path };
        if let Ok(content) = fs::read_to_string(&config.path) {
            for raw in content.lines() {
                let line = raw.trim();
                if line.is_empty() || line.starts_with(';') || line.starts_with('#') {
                    continue;
                }
                if let Some(eq) = line.find('=') {
                    if eq == 0 {
                        continue;
                    }
                    let key = line[..eq].trim().to_lowercase();
                    let value = line[eq + 1..].trim().to_string();
                    config.values.insert(key, value);
                }
            }
        }
        config
    }

    pub fn get(&self, key: &str) -> Option<&String> {
        self.values.get(&key.to_lowercase())
    }

    pub fn set(&mut self, key: &str, value: impl Into<String>) {
        self.values.insert(key.to_lowercase(), value.into());
    }

    pub fn save(&self) {
        let mut out = String::from(
            "# Taskly configuration\n# This file is automatically generated and managed by Taskly.\n",
        );
        let mut pairs: Vec<(&String, &String)> = self.values.iter().collect();
        pairs.sort();
        for (key, value) in pairs {
            out.push_str(&format!("{key}={value}\n"));
        }
        let _ = fs::write(&self.path, out);
    }

    pub fn last_db_path(&self) -> Option<String> {
        self.get("last-db-path")
            .or_else(|| self.get("last_db_path"))
            .cloned()
    }

    pub fn language(&self) -> String {
        self.get("language").cloned().unwrap_or_else(|| "zh".into())
    }

    pub fn last_selected_list_id(&self) -> i64 {
        self.get("last-selected-list-id")
            .and_then(|v| v.parse().ok())
            .unwrap_or(0)
    }
}
