#lang racket/base

(require racket/file
         racket/list
         racket/path
         racket/string
         "paths.rkt")

(provide read-config
         write-config!
         config-ref
         config-language
         config-last-selected-list-id
         resolve-database-path)

(define (normalize-key key)
  (string-downcase (string-trim key)))

(define (read-config [path (config-file-path)])
  (define result (make-hash))
  (when (file-exists? path)
    (call-with-input-file
     path
     (lambda (in)
       (for ([raw (in-lines in)])
         (define line (string-trim raw))
         (unless (or (string=? line "")
                     (string-prefix? line "#")
                     (string-prefix? line ";"))
           (define match-result (regexp-match #px"^([^=]+)=(.*)$" line))
           (when match-result
             (hash-set! result
                        (normalize-key (list-ref match-result 1))
                        (string-trim (list-ref match-result 2)))))))))
  result)

(define (config-ref config key [default #f])
  (hash-ref config (normalize-key key) default))

(define (config-language config)
  (define value (string-downcase (or (config-ref config "language") "zh")))
  (if (member value '("zh" "en")) value "zh"))

(define (config-last-selected-list-id config)
  (define value (config-ref config "last-selected-list-id" "0"))
  (define parsed (string->number value))
  (if (and parsed (exact-integer? parsed)) parsed 0))

(define (write-config! config [path (config-file-path)])
  (define parent (path-only path))
  (when parent (make-directory* parent))
  (call-with-output-file
   path
   #:exists 'truncate/replace
   (lambda (out)
     (displayln "# Taskly configuration" out)
     (displayln "# This file is automatically generated and managed by Taskly." out)
     (for ([key (in-list '("last-db-path" "language" "last-selected-list-id"))])
       (define value (config-ref config key #f))
       (when value
         (fprintf out "~a = ~a\n" key value)))))))

(define (resolve-database-path [override #f] [config (read-config)])
  (cond
    [override (path->complete-path override)]
    [else
     (define configured
       (or (config-ref config "last-db-path" #f)
           (config-ref config "last_db_path" #f)))
     (if (and configured (not (string=? configured "")))
         (path->complete-path configured)
         (default-database-path))]))
